#!/usr/bin/env node

var path = require("path");
var fs = require("fs");

var stream = fs.createReadStream(__dirname + "/../posts", "utf8");

var data = "", files = [];
stream.on("data", function(line){
  data += line;
});

stream.on("end", getTitles);

function getTitles(){
  data.split("\n").forEach(function(line){
    if(line.length) {
      files.push(line.split(" ")[1]);
    }
  });
  files.reverse();

  var posts = files.map(function(base){
    var link = "posts/" + base+ ".html";
    var title = getTitle(link);
    return { link: link, title: title };
  });

  console.log(JSON.stringify({posts:posts}));
}

function getTitle(fileNamePart){
  var fn = __dirname + "/../dist/" + fileNamePart;
  var cont = fs.readFileSync(fn, "utf8");
  var title = /<title>(.+)\ \|/.exec(cont)[1];
  return title;
}
